// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7: koneksi runtime dipegang driver adapter (src/lib/prisma.ts).
    // Config ini dipakai Prisma CLI (generate/migrate/db).
    url: process.env["DATABASE_URL"],
  },
});
